spring.datasource:
  driver-class-name: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://127.0.0.1:3306/testdb
  username: skku
  password: skku

spring.sql.init.mode: ALWAYS
spring.jpa:
  hibernate.ddl-auto: update
  defer-datasource-initialization: true

#  스프링부트 2.2부터는 put, delete 사용을 위해 HiddenMethodFilter 설정이 별도로 필요함
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
